SELECT TIPO_DOCUMENTO,NUM_DOCUMENTO,CODIGO_PRODUCTO FROM FACTURA
WHERE TIPO_DOCUMENTO LIKE "Cedula" AND NUM_DOCUMENTO LIKE "1039474422";

SELECT TIPO_DOCUMENTO,NUM_DOCUMENTO,CODIGO_PRODUCTO FROM FACTURA
WHERE TIPO_DOCUMENTO LIKE "Cedula" AND NUM_DOCUMENTO LIKE "1039469347";

SELECT TIPO_DOCUMENTO,NUM_DOCUMENTO,CODIGO_PRODUCTO FROM FACTURA
WHERE TIPO_DOCUMENTO LIKE "Pasaporte" AND NUM_DOCUMENTO LIKE "ATQ3456";

SELECT TIPO_DOCUMENTO,NUM_DOCUMENTO,CODIGO_PRODUCTO FROM FACTURA
WHERE TIPO_DOCUMENTO LIKE "Cedula" AND NUM_DOCUMENTO LIKE "42824459";

SELECT TIPO_DOCUMENTO,NUM_DOCUMENTO,CODIGO_PRODUCTO FROM FACTURA
WHERE TIPO_DOCUMENTO LIKE "Cedula" AND NUM_DOCUMENTO LIKE "1039469243";


SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Huevos","Huevos AAA");

SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Repollo Morado");

SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Pan Tajado");

SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Jamon");

SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Leche");

SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Muslos de pollo");

SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Lechuga");

SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Tomate");

SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Zanahoria");

SELECT NOMBRE_PRODUCTO,NIT_PROVEEDOR FROM PROVEE 
WHERE NOMBRE_PRODUCTO IN ("Papa Capira");